### PR TITLE
Resize window and panes

### PR DESCRIPTION
**Pull request by nminnie**
User can now resize the browser window and the 3 inner panes (class names, classifier glyphs, page glyphs panes) without lag/delay.

@vigliensoni 
Please let me know if you find any bugs. Thank you!

### CODE REVIEW

**Comment by vigliensoni** [comment]
The main issues have been fixed. However, there are still other ones that can be improved:

- the name of classes disappear after shortening and widening the browser window
- when shortening the window, the black navigation bar gets twice the height (bootstrap problem?)
- after shortening the window, the scroll bar of the class neumes is rendered on top of the navigation bar
- after playing a bit with window resizing, the behaviour is still buggy. See the image

screen shot 2018-08-02 at 1 35 33 pm



On other note, still there is plenty of space in the the classifier panes to display glyphs.

**Comment by nminnie** [comment]
@vigliensoni 
Thank you for the feedback! I'll work on these issues.

**Comment by nminnie** [comment]
@vigliensoni 
Were you using Firefox to test?

**Comment by vigliensoni** [comment]
Yes, I was.

**Comment by nminnie** [comment]
@vigliensoni 
When you said "after shortening the window, the scroll bar of the class neumes is rendered on top of the navigation bar", by "class neumes" do you mean class names or classifier glyphs?

**Comment by vigliensoni** [comment]
Autocorrection devil! I meant class names.

**Comment by nminnie** [comment]
@vigliensoni 
In response to your 4 points:
1. the name of classes disappear after shortening and widening the browser window: Actually, the class names do not disappear but are moved down (to the center of that class' glyph collection), so you would have to scroll down a bit to see them.
2. when shortening the window, the black navigation bar gets twice the height: I've fixed this issue to maintain the height of the navigation bar.
3. after shortening the window, the scroll bar of the class names is rendered on top of the navigation bar: This scrollbar is actually always below the navigation bar, even when the IC window is opened for the first time. This is not caused by resizing the browser window.
4. after playing a bit with window resizing, the behaviour is still buggy: I have been playing around with resizing the panes and window but could not replicate the buggy behavior, both on Chrome and Firefox. It has been working fine for me. Could be sit together to test it again perhaps?

**Comment by vigliensoni** [comment]
I think the behaviour is much better now. When resizing vertically, though,
the proportion of the three panes is not preserved. In other words, the
lower pane (i.e., preview image pane) is the one usually hidden first. This
behaviour is different when resizing horizontally.

**Comment by nminnie** [comment]
@vigliensoni 
The vertical proportions of the three panes on the right is now preserved

**Comment by nminnie** [comment]
@vigliensoni 
The vertical and horizontal proportions are now maintained when resizing the window, and I've added handling for the collapse button.
I think this functionality is (finally) finished.

**Pull request merged**
